---

---
engines:
  sonarvb:
    exclude_paths:
      - "Logs"
    config:
      languages:
        - "visualbasic"
        
languages:
  visualbasic:
    extensions:
      - ".bas"
      - ".cls"
      - ".vbp"
      - ".vb"
